[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm i -g pnpm", "pnpm install"]

[phases.build]
cmds = ["pnpm db:generate", "pnpm build"]

[start]
cmd = "pnpm db:push && node dist/index.js"
